name: CI JoomGallery

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # or your PHP version
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev --no-scripts --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader

      - name: Clean up unnecessary files
        run: |
          rm -rf crowdin.yml composer.json composer.lock header.txt phpstan.neon ruleset.xml docs tests tools .github .editorconfig

      - name: Cleanup pel directory
        run: |
          PEL_DIR="administrator/com_joomgallery/vendor/fileeye/pel"
          find "$PEL_DIR" -mindepth 1 -maxdepth 1 ! -name 'src' ! -name 'autoload.php' ! -name 'composer.json' -exec rm -rf {} +

      - name: Get tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Zip the build
        run: |
          zip -r JoomGallery-${{ steps.get_tag.outputs.TAG_NAME }}.zip . -x '*.git*'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_tag.outputs.TAG_NAME }}
          tag_name: ${{ steps.get_tag.outputs.TAG_NAME }}
          files: JoomGallery-${{ steps.get_tag.outputs.TAG_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
